using LedgerAndField.Api.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace LedgerAndField.Api.Services;

public class ChangeOrderPdfService
{
    public ChangeOrderPdfService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] Build(Project project, Opportunity opp, ChangeRequest cr)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Header().Column(col =>
                {
                    col.Item().Text("SCOPELINE — SCOPE & REVENUE RECOVERY").Bold().FontSize(10).FontColor(Colors.Grey.Darken2);
                    col.Item().Text("SCOPE CHANGE REQUEST").FontSize(20).Bold().FontColor(Colors.BlueGrey.Darken4);
                    col.Item().Text($"{cr.Number}  ·  {cr.Status.ToUpperInvariant()}  ·  {DateTime.UtcNow:MMM d, yyyy}").FontSize(11);
                });
                page.Content().Column(col =>
                {
                    col.Spacing(12);
                    col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("PROJECT").Bold().FontSize(9).FontColor(Colors.Grey.Darken1);
                            c.Item().Text(project.Name).FontSize(12).Bold();
                            c.Item().Text($"Agreed Scope: {project.ScopeValue:C0} ({project.Currency})").FontSize(10);
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("CLIENT").Bold().FontSize(9).FontColor(Colors.Grey.Darken1);
                            c.Item().Text(project.ClientName).FontSize(12).Bold();
                        });
                    });
                    col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                    
                    col.Item().Text("REASON / CATEGORY").Bold().FontSize(10).FontColor(Colors.Grey.Darken1);
                    col.Item().Text(cr.Reason ?? opp.Type).FontSize(11);

                    col.Item().Text("SOW / CONTRACT REFERENCE").Bold().FontSize(10).FontColor(Colors.Grey.Darken1);
                    col.Item().Text(opp.Clause ?? "Standard Scope Variation Terms").FontSize(11);

                    col.Item().Text("CHANGED SCOPE DESCRIPTION").Bold().FontSize(10).FontColor(Colors.Grey.Darken1);
                    col.Item().Text(cr.ChangedScope ?? opp.Description).FontSize(11);

                    col.Item().Text("COST BREAKDOWN & PRICING").Bold().FontSize(10).FontColor(Colors.Grey.Darken1);
                    col.Item().Text(cr.CostBreakdown ?? $"Estimated cost: {opp.EstimatedCost:C0}. Proposed billable value: {opp.BillableValue:C0}.").FontSize(11);

                    col.Item().Text("PROPOSED RECOVERABLE VALUE").Bold().FontSize(10).FontColor(Colors.Grey.Darken1);
                    col.Item().Text($"{opp.BillableValue:C0}").FontSize(14).Bold().FontColor(Colors.Orange.Darken2);

                    col.Item().Text("SUPPORTING EVIDENCE & LOGS").Bold().FontSize(10).FontColor(Colors.Grey.Darken1);
                    foreach (var e in opp.Evidence)
                    {
                        col.Item().Text($"• {e.Text}  [SOURCE: {e.Source}]").FontSize(10);
                    }
                });
                page.Footer().AlignCenter().Text("Generated by Scopeline — Grounded in uploaded project activity and SOW clauses.").FontSize(9).FontColor(Colors.Grey.Darken1);
            });
        }).GeneratePdf();
    }
}
